--CREATE DATABASE ldw_fonpell COLLATE Latin1_General_100_BIN2_UTF8
use ldh_codisal

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'NJcaE3Uk5v@V(G#-9?d='

CREATE DATABASE SCOPED CREDENTIAL WorkspaceIdentity
WITH IDENTITY = 'Managed Identity'

EXEC('CREATE SCHEMA bronze AUTHORIZATION dbo')
EXEC('CREATE SCHEMA gold AUTHORIZATION dbo')
EXEC('CREATE SCHEMA silver AUTHORIZATION dbo')
EXEC('CREATE SCHEMA helpers AUTHORIZATION dbo')
EXEC('CREATE SCHEMA frontend AUTHORIZATION dbo')

CREATE EXTERNAL DATA SOURCE eds_delfos
	WITH (
		LOCATION   = 'https://adlsdelfosanalytics.blob.core.windows.net/codisal' ,
		CREDENTIAL =  WorkspaceIdentity  
	    );

CREATE EXTERNAL FILE FORMAT eff_delfos_csv
    WITH (  
        FORMAT_TYPE = DELIMITEDTEXT
		,FORMAT_OPTIONS (
				FIELD_TERMINATOR = N'|', 
				FIRST_ROW = 2, 
				USE_TYPE_DEFAULT = False
		)
    );

CREATE EXTERNAL FILE FORMAT eff_delfos_parquet
	WITH ( FORMAT_TYPE = PARQUET)