DECLARE @StartDate DATE
DECLARE @EndDate DATE
DECLARE @Date DATE
    
DECLARE @Year INT
DECLARE @Month INT
DECLARE @Day INT

DECLARE @SQL NVARCHAR(4000) 
DECLARE @Version INT

DECLARE @dateFormat AS varchar(14) = '00000000000000'
DECLARE @folderName as VARCHAR(100)

DECLARE @ErrorNum INT
DECLARE @ErrorMsg VARCHAR(500)
DROP TABLE IF EXISTS #Dates
CREATE TABLE #Dates (FechaFac DATE)
INSERT INTO #Dates EXEC helpers.spGetDatesToUpdate

-- Setup folders
SET @StartDate = (SELECT MIN(FechaFac) FROM #Dates)
SET @EndDate = (SELECT MAX(FechaFac) FROM #Dates)
SET @Date = @StartDate
WHILE @Date <= @EndDate
BEGIN
	SET @Year = YEAR(@Date)
    SET @Month = MONTH(@Date)
    SET @Day = DAY(@Date)
    SET @Version = 0
	SET @folderName = CONCAT('/chess/parquet_files/ventasresumen/Year=',
								CAST(@Year as VARCHAR(4)), 
								'/Month=', CAST(@Month as VARCHAR(2)),
								'/Day=',CAST(@Day as VARCHAR(2)),
								'/Ver=',CAST(@Version AS VARCHAR(10)),'/',
								@dateFormat,'/')
	
	SET @SQL ='
			CREATE EXTERNAL TABLE VentasResumen' + CAST(@Year as VARCHAR(4)) + CAST(@Month as VARCHAR(2)) + CAST(@Day as VARCHAR(2)) +'#v'+ CAST(@Version AS VARCHAR(10)) + 
			' WITH (
					LOCATION = ''' + @folderName +''',
					DATA_SOURCE = eds_delfos,  
					FILE_FORMAT = eff_delfos_parquet
				)  
			AS
			SELECT 
				CAST( NULL AS int) AS idEmpresa,
				CAST( NULL AS nvarchar(100)) AS dsEmpresa,
				CAST( NULL AS nvarchar(10)) AS idDocumento,
				CAST( NULL AS nvarchar(50)) AS dsDocumento,
				CAST( NULL AS nvarchar(2)) AS letra,
				CAST( NULL AS int) AS serie,
				CAST( NULL AS int) AS nrodoc,
				CAST( NULL AS nvarchar(2)) AS pickup,
				CAST( NULL AS nvarchar(2)) AS anulado,
				CAST( NULL AS int) AS idMovComercial,
				CAST( NULL AS nvarchar(100)) AS dsMovComercial,
				CAST( NULL AS int) AS idRechazo,
				CAST( NULL AS nvarchar(100)) AS dsRechazo,
				CAST(''' + CAST(@Date AS varchar(10)) + ''' AS datetime) AS fechaComprobate,
				CAST( NULL AS date) AS fechaAnulacion,
				CAST( NULL AS date) AS fechaAlta,
				CAST( NULL AS nvarchar(100)) AS usuarioAlta,
				CAST( NULL AS date) AS fechaVencimiento,
				CAST( NULL AS date) AS fechaEntrega,
				CAST( NULL AS int) AS idSucursal,
				CAST( NULL AS nvarchar(100)) AS dsSucursal,
				CAST( NULL AS int) AS idFuerzaVentas,
				CAST( NULL AS nvarchar(100)) AS dsFuerzaVentas,
				CAST( NULL AS int) AS idDeposito,
				CAST( NULL AS nvarchar(100)) AS dsDeposito,
				CAST( NULL AS int) AS idVendedor,
				CAST( NULL AS nvarchar(100)) AS dsVendedor,
				CAST( NULL AS int) AS idSupervisor,
				CAST( NULL AS nvarchar(100)) AS dsSupervisor,
				CAST( NULL AS int) AS idGerente,
				CAST( NULL AS nvarchar(100)) AS dsGerente,
				CAST( NULL AS nvarchar(100)) AS tipoConstribuyente,
				CAST( NULL AS nvarchar(100)) AS dsTipoConstribuyente,
				CAST( NULL AS int) AS idTipoPago,
				CAST( NULL AS nvarchar(100)) AS dsTipoPago,
				CAST( NULL AS date) AS fechaPago,
				CAST( NULL AS int) AS idPedido,
				CAST( NULL AS date) AS fechaPedido,
				CAST( NULL AS nvarchar(100)) AS origen,
				CAST( NULL AS nvarchar(100)) AS idorigen,
				CAST( NULL AS nvarchar(100)) AS planillaCarga,
				CAST( NULL AS int) AS idFleteroCarga,
				CAST( NULL AS nvarchar(100)) AS dsFleteroCarga,
				CAST( NULL AS int) AS idLiquidacion,
				CAST( NULL AS date) AS fechaLiquidacion,
				CAST( NULL AS int) AS idCaja,
				CAST( NULL AS date) AS fechaCaja,
				CAST( NULL AS nvarchar(100)) AS cajero,
				CAST( NULL AS int) AS idCliente,
				CAST( NULL AS nvarchar(100)) AS nombreCliente,
				CAST( NULL AS nvarchar(500)) AS domicilioCliente,
				CAST( NULL AS int) AS codigoPostal,
				CAST( NULL AS nvarchar(100)) AS dsLocalidad,
				CAST( NULL AS nvarchar(100)) AS idProvincia,
				CAST( NULL AS nvarchar(100)) AS dsProvincia,
				CAST( NULL AS int) AS idNegocio,
				CAST( NULL AS nvarchar(100)) AS dsNegocio,
				CAST( NULL AS int) AS idAgrupacion,
				CAST( NULL AS nvarchar(100)) AS dsAgrupacion,
				CAST( NULL AS int) AS idArea,
				CAST( NULL AS nvarchar(100)) AS dsArea,
				CAST( NULL AS int) AS idSegmentoMkt,
				CAST( NULL AS nvarchar(100)) AS dsSegmentoMkt,
				CAST( NULL AS int) AS idCanalMkt,
				CAST( NULL AS nvarchar(100)) AS dsCanalMkt,
				CAST( NULL AS int) AS idSubcanalMkt,
				CAST( NULL AS nvarchar(100)) AS dsSubcanalMKT,
				CAST( NULL AS int) AS idLinea,
				CAST( NULL AS int) AS idArticulo,
				CAST( NULL AS nvarchar(100)) AS dsArticulo,
				CAST( NULL AS int) AS idConcepto,
				CAST( NULL AS nvarchar(100)) AS dsConcepto,
				CAST( NULL AS nvarchar(100)) AS esCombo,
				CAST( NULL AS int) AS idCombo,
				CAST( NULL AS int) AS idArticuloEstadistico,
				CAST( NULL AS nvarchar(100)) AS dsArticuloEstadistico,
				CAST( NULL AS int) AS presentacionArticulo,
				CAST( NULL AS int) AS cantidadPorPallets,
				CAST( NULL AS decimal(14,4)) AS peso,
				CAST( NULL AS date) AS fechaAsientoContable,
				CAST( NULL AS int) AS nroAsientoContable,
				CAST( NULL AS int) AS nroPlanContable,
				CAST( NULL AS int) AS codCuentaContable,
				CAST( NULL AS int) AS idCentroCosto,
				CAST( NULL AS nvarchar(100)) AS dsCuentaContable,
				CAST( NULL AS int) AS cantidadSolicitada,
				CAST( NULL AS int) AS unidadesSolicitadas,
				CAST( NULL AS decimal(14,4)) AS cantidadesCorCargo,
				CAST( NULL AS decimal(14,4)) AS cantidadesSinCargo,
				CAST( NULL AS decimal(14,4)) AS cantidadesTotal,
				CAST( NULL AS decimal(14,4)) AS pesoTotal,
				CAST( NULL AS decimal(14,4)) AS cantidadesRechazo,
				CAST( NULL AS decimal(14,4)) AS unimedcargo,
				CAST( NULL AS decimal(14,4)) AS unimedscargo,
				CAST( NULL AS decimal(14,4)) AS unimedtotal,
				CAST( NULL AS decimal(14,4)) AS precioUnitarioBruto,
				CAST( NULL AS decimal(14,4)) AS bonificacion,
				CAST( NULL AS decimal(14,4)) AS precioUnitarioNeto,
				CAST( NULL AS decimal(14,4)) AS subtotalBruto,
				CAST( NULL AS decimal(14,4)) AS subtotalBonificado,
				CAST( NULL AS decimal(14,4)) AS subtotalNeto,
				CAST( NULL AS decimal(14,4)) AS iva21,
				CAST( NULL AS decimal(14,4)) AS iva27,
				CAST( NULL AS decimal(14,4)) AS per3337,
				CAST( NULL AS decimal(14,4)) AS iva2,
				CAST( NULL AS decimal(14,4)) AS percepcion212,
				CAST( NULL AS decimal(14,4)) AS percepcioniibb,
				CAST( NULL AS decimal(14,4)) AS internos,
				CAST( NULL AS decimal(14,4)) AS subtotalFinal,
				CAST( NULL AS decimal(14,4)) AS tradespendg,
				CAST( NULL AS decimal(14,4)) AS tradespends,
				CAST( NULL AS decimal(14,4)) AS tradespendb,
				CAST( NULL AS decimal(14,4)) AS tradespendi,
				CAST( NULL AS decimal(14,4)) AS tradespendp,
				CAST( NULL AS decimal(14,4)) AS tradespendt,
				CAST( NULL AS decimal(14,4)) AS totradspend,
				CAST( NULL AS nvarchar(100)) AS acciones,
				CAST( NULL AS nvarchar(100)) AS persiibbd,
				CAST( NULL AS nvarchar(100)) AS persiibbr,
				CAST( NULL AS nvarchar(100)) AS numerosserie,
				CAST( NULL AS nvarchar(100)) AS numerosactivo,
				CAST( NULL AS nvarchar(100)) AS cuentayorden,
				CAST( NULL AS int) AS codprovcyo,
				CAST( NULL AS nvarchar(100)) AS descrip,
				CAST( NULL AS int) AS nrorendcyo,
				CAST( NULL AS int) AS idTipoCambio,
				CAST( NULL AS nvarchar(100)) AS dsTipoCambio,
				CAST( NULL AS nvarchar(100)) AS cfdiEmitido,
				CAST( NULL AS nvarchar(100)) AS regimenFiscal,
				CAST( NULL AS nvarchar(100)) AS informado,
				CAST( NULL AS nvarchar(100)) AS firmadigital,
				CAST( NULL AS nvarchar(100)) AS proveedor,
				CAST( NULL AS nvarchar(100)) AS fvigpcompra,
				CAST( NULL AS decimal(14,4)) AS preciocomprabr,
				CAST( NULL AS decimal(14,4)) AS preciocomprant,
				CAST( NULL AS nvarchar(100)) AS lineaCredito,
				CAST( NULL AS nvarchar(100)) AS tipocambio,
				CAST( NULL AS int) AS motivocambio,
				CAST( NULL AS nvarchar(100)) AS descmotcambio,
				CAST( NULL AS nvarchar(100)) AS numeracionFiscal,
				CAST( NULL AS nvarchar(100)) AS codproviibb,
				CAST( NULL AS int) AS TipoId,
				CAST( NULL AS nvarchar(100)) AS DescripcionId,
				CAST( NULL AS nvarchar(100)) AS Identificador,
				CAST(0 AS INT) as Ver
	'
	
	BEGIN TRY
		EXEC (@SQL)
	END TRY
	BEGIN CATCH
		SET @ErrorNum = ERROR_NUMBER()
		IF @ErrorNum <> 15842 THROW
	END CATCH

	IF EXISTS ( SELECT * FROM sys.external_tables 
        		WHERE object_id = OBJECT_ID('VentasResumen' + CAST(@Year as VARCHAR(4)) + CAST(@Month as VARCHAR(2)) + CAST(@Day as VARCHAR(2)) +'#v'+ CAST(@Version AS VARCHAR(10))))
	BEGIN
		SET @SQL = 'DROP EXTERNAL TABLE VentasResumen' + CAST(@Year as VARCHAR(4)) + CAST(@Month as VARCHAR(2)) + CAST(@Day as VARCHAR(2)) +'#v'+ CAST(@Version AS VARCHAR(10))
		EXEC(@SQL)
	END

	IF NOT EXISTS ( SELECT * FROM sys.external_tables WHERE object_id = OBJECT_ID('silver.VentasResumen'))
	BEGIN
		CREATE EXTERNAL TABLE silver.VentasResumen (
			idEmpresa int,
			dsEmpresa nvarchar(100),
			idDocumento nvarchar(10),
			dsDocumento nvarchar(50),
			letra nvarchar(2),
			serie int,
			nrodoc int,
			pickup nvarchar(2),
			anulado nvarchar(2),
			idMovComercial int,
			dsMovComercial nvarchar(100),
			idRechazo int,
			dsRechazo nvarchar(100),
			fechaComprobate datetime,
			fechaAnulacion date,
			fechaAlta date,
			usuarioAlta nvarchar(100),
			fechaVencimiento date,
			fechaEntrega date,
			idSucursal int,
			dsSucursal nvarchar(100),
			idFuerzaVentas int,
			dsFuerzaVentas nvarchar(100),
			idDeposito int,
			dsDeposito nvarchar(100),
			idVendedor int,
			dsVendedor nvarchar(100),
			idSupervisor int,
			dsSupervisor nvarchar(100),
			idGerente int,
			dsGerente nvarchar(100),
			tipoConstribuyente nvarchar(100),
			dsTipoConstribuyente nvarchar(100),
			idTipoPago int,
			dsTipoPago nvarchar(100),
			fechaPago date,
			idPedido int,
			fechaPedido date,
			origen nvarchar(100),
			idorigen nvarchar(100),
			planillaCarga nvarchar(100),
			idFleteroCarga int,
			dsFleteroCarga nvarchar(100),
			idLiquidacion int,
			fechaLiquidacion date,
			idCaja int,
			fechaCaja date,
			cajero nvarchar(100),
			idCliente int,
			nombreCliente nvarchar(100),
			domicilioCliente nvarchar(500),
			codigoPostal int,
			dsLocalidad nvarchar(100),
			idProvincia nvarchar(100),
			dsProvincia nvarchar(100),
			idNegocio int,
			dsNegocio nvarchar(100),
			idAgrupacion int,
			dsAgrupacion nvarchar(100),
			idArea int,
			dsArea nvarchar(100),
			idSegmentoMkt int,
			dsSegmentoMkt nvarchar(100),
			idCanalMkt int,
			dsCanalMkt nvarchar(100),
			idSubcanalMkt int,
			dsSubcanalMKT nvarchar(100),
			idLinea int,
			idArticulo int,
			dsArticulo nvarchar(100),
			idConcepto int,
			dsConcepto nvarchar(100),
			esCombo nvarchar(100),
			idCombo int,
			idArticuloEstadistico int,
			dsArticuloEstadistico nvarchar(100),
			presentacionArticulo int,
			cantidadPorPallets int,
			peso decimal(14, 4),
			fechaAsientoContable date,
			nroAsientoContable int,
			nroPlanContable int,
			codCuentaContable int,
			idCentroCosto int,
			dsCuentaContable nvarchar(100),
			cantidadSolicitada int,
			unidadesSolicitadas int,
			cantidadesCorCargo decimal(14, 4),
			cantidadesSinCargo decimal(14, 4),
			cantidadesTotal decimal(14, 4),
			pesoTotal decimal(14, 4),
			cantidadesRechazo decimal(14, 4),
			unimedcargo decimal(14, 4),
			unimedscargo decimal(14, 4),
			unimedtotal decimal(14, 4),
			precioUnitarioBruto decimal(14, 4),
			bonificacion decimal(14, 4),
			precioUnitarioNeto decimal(14, 4),
			subtotalBruto decimal(14, 4),
			subtotalBonificado decimal(14, 4),
			subtotalNeto decimal(14, 4),
			iva21 decimal(14, 4),
			iva27 decimal(14, 4),
			per3337 decimal(14, 4),
			iva2 decimal(14, 4),
			percepcion212 decimal(14, 4),
			percepcioniibb decimal(14, 4),
			internos decimal(14, 4),
			subtotalFinal decimal(14, 4),
			tradespendg decimal(14, 4),
			tradespends decimal(14, 4),
			tradespendb decimal(14, 4),
			tradespendi decimal(14, 4),
			tradespendp decimal(14, 4),
			tradespendt decimal(14, 4),
			totradspend decimal(14, 4),
			acciones nvarchar(100),
			persiibbd nvarchar(100),
			persiibbr nvarchar(100),
			numerosserie nvarchar(100),
			numerosactivo nvarchar(100),
			cuentayorden nvarchar(100),
			codprovcyo int,
			descrip nvarchar(100),
			nrorendcyo int,
			idTipoCambio int,
			dsTipoCambio nvarchar(100),
			cfdiEmitido nvarchar(100),
			regimenFiscal nvarchar(100),
			informado nvarchar(100),
			firmadigital nvarchar(100),
			proveedor nvarchar(100),
			fvigpcompra nvarchar(100),
			preciocomprabr decimal(14, 4),
			preciocomprant decimal(14, 4),
			lineaCredito nvarchar(100),
			tipocambio nvarchar(100),
			motivocambio int,
			descmotcambio nvarchar(100),
			numeracionFiscal nvarchar(100),
			codproviibb nvarchar(100),
			TipoId int,
			DescripcionId nvarchar(100),
			Identificador nvarchar(100),
			Ver INT)
		WITH (
				LOCATION = 'chess/parquet_files/ventasresumen/Year=*/Month=*/Day=*/Ver=*/*/*.parquet',
				DATA_SOURCE = eds_delfos,  
				FILE_FORMAT = eff_delfos_parquet
			)
	END

	SET @Date = DATEADD(day,1,@Date)
END